CREATE TABLE [User] (userId int IDENTITY NOT NULL, email varchar(50) NOT NULL UNIQUE, password varchar(255) NOT NULL, phone varchar(20) NOT NULL, roleId int NOT NULL, PRIMARY KEY (userId));
CREATE TABLE Venue (venueId int IDENTITY NOT NULL, userId int NOT NULL, name varchar(30) NOT NULL, addressLine1 varchar(50) NOT NULL, addressLine2 varchar(50) NULL, stateId int NOT NULL, suburb varchar(30) NOT NULL, postcode varchar(6) NOT NULL, capacity int NOT NULL, active bit NOT NULL, description varchar(255) NOT NULL, hourlyPrice decimal(19, 2) NOT NULL, PRIMARY KEY (venueId));
CREATE TABLE Booking (bookingId int IDENTITY NOT NULL, userId int NOT NULL, venueId int NOT NULL, statusId int NOT NULL, startDateTime date NOT NULL, eventName varchar(255) NOT NULL, guests int NOT NULL, duration int NOT NULL, abn varchar(20) NULL, licensePhoto varchar(100) NULL, liabilityDoc varchar(100) NULL, abnDoc varchar(100) NULL, dateSubmitted date NOT NULL, PRIMARY KEY (bookingId));
CREATE TABLE Shortlist (userId int NOT NULL, venueId int NOT NULL, ranking int NOT NULL, PRIMARY KEY (userId, venueId));
CREATE TABLE Review (reviewId int IDENTITY NOT NULL, bookingId int NOT NULL, rating decimal(2, 1) NOT NULL, comment varchar(255) NULL, createdAt date NOT NULL, PRIMARY KEY (reviewId));
CREATE TABLE Suitability (suitabilityId int IDENTITY NOT NULL, name varchar(30) NOT NULL, PRIMARY KEY (suitabilityId));
CREATE TABLE State (stateId int IDENTITY NOT NULL, state varchar(20) NOT NULL, PRIMARY KEY (stateId));
CREATE TABLE Image (imageId int IDENTITY NOT NULL, venueId int NOT NULL, path varchar(255) NOT NULL, PRIMARY KEY (imageId));
CREATE TABLE VenueSuitability (venueId int NOT NULL, suitabilityId int NOT NULL, PRIMARY KEY (venueId, suitabilityId));
CREATE TABLE Role (roleId int IDENTITY NOT NULL, roleName varchar(15) NOT NULL UNIQUE, PRIMARY KEY (roleId));
CREATE TABLE Person (userId int NOT NULL, firstName varchar(20) NOT NULL, lastName varchar(20) NOT NULL, PRIMARY KEY (userId));
CREATE TABLE Vendor (userId int NOT NULL, businessName varchar(50) NOT NULL, PRIMARY KEY (userId));
CREATE TABLE Blockouts (blockoutId int IDENTITY NOT NULL, venueId int NOT NULL, startDate date NOT NULL, endDate date NOT NULL, PRIMARY KEY (blockoutId));
CREATE TABLE BookingStatus (statusId int IDENTITY NOT NULL, statusName varchar(20) NOT NULL, PRIMARY KEY (statusId));
CREATE UNIQUE INDEX User_userId ON [User] (userId);
CREATE UNIQUE INDEX Venue_venueId ON Venue (venueId);
CREATE UNIQUE INDEX Booking_bookingId ON Booking (bookingId);
CREATE INDEX Shortlist_ranking ON Shortlist (ranking);
CREATE UNIQUE INDEX Review_reviewId ON Review (reviewId);
CREATE UNIQUE INDEX Suitability_suitabilityId ON Suitability (suitabilityId);
CREATE UNIQUE INDEX State_stateId ON State (stateId);
CREATE UNIQUE INDEX State_state ON State (state);
CREATE UNIQUE INDEX Image_imageId ON Image (imageId);
CREATE UNIQUE INDEX Role_roleId ON Role (roleId);
CREATE UNIQUE INDEX Blockouts_blockoutId ON Blockouts (blockoutId);
CREATE INDEX Blockouts_venueId ON Blockouts (venueId);
CREATE UNIQUE INDEX BookingStatus_statusId ON BookingStatus (statusId);
ALTER TABLE Shortlist ADD CONSTRAINT Has FOREIGN KEY (userId) REFERENCES [User] (userId);
ALTER TABLE VenueSuitability ADD CONSTRAINT FKVenueSuita774414 FOREIGN KEY (venueId) REFERENCES Venue (venueId);
ALTER TABLE VenueSuitability ADD CONSTRAINT FKVenueSuita146162 FOREIGN KEY (suitabilityId) REFERENCES Suitability (suitabilityId);
ALTER TABLE Person ADD CONSTRAINT FKPerson702841 FOREIGN KEY (userId) REFERENCES [User] (userId);
ALTER TABLE Vendor ADD CONSTRAINT FKVendor344344 FOREIGN KEY (userId) REFERENCES [User] (userId);
ALTER TABLE [User] ADD CONSTRAINT FKUser635666 FOREIGN KEY (roleId) REFERENCES Role (roleId);
ALTER TABLE Venue ADD CONSTRAINT FKVenue432303 FOREIGN KEY (stateId) REFERENCES State (stateId);
ALTER TABLE Image ADD CONSTRAINT FKImage239727 FOREIGN KEY (venueId) REFERENCES Venue (venueId);
ALTER TABLE Shortlist ADD CONSTRAINT [References] FOREIGN KEY (venueId) REFERENCES Venue (venueId);
ALTER TABLE Blockouts ADD CONSTRAINT FKBlockouts258506 FOREIGN KEY (venueId) REFERENCES Venue (venueId);
ALTER TABLE Booking ADD CONSTRAINT FKBooking537964 FOREIGN KEY (statusId) REFERENCES BookingStatus (statusId);
ALTER TABLE Booking ADD CONSTRAINT FKBooking151519 FOREIGN KEY (venueId) REFERENCES Venue (venueId);
ALTER TABLE Venue ADD CONSTRAINT Manages FOREIGN KEY (userId) REFERENCES [User] (userId);
ALTER TABLE Booking ADD CONSTRAINT FKBooking923691 FOREIGN KEY (userId) REFERENCES [User] (userId);
ALTER TABLE Review ADD CONSTRAINT FKReview372739 FOREIGN KEY (bookingId) REFERENCES Booking (bookingId);
